### PR TITLE
Incremental export bugfix

### PR DESCRIPTION
**Pull request by ehoelzl**
This PR is a minor bugfix for exporting Issues using the `--incremental` flag.
----
Previously, when importing issues of the same Journal, sometimes some issues fail for no apparent reason. When re-running on those failed issues, the whole `.jsonl.bz2` file is overwritten, and all previous work is lost for that given year (only for issues, since pages are per Issue).

The code was modified to take into account this possibility by simply checking if the file exists, and removing issues that need to be over-written, and then appends the new ones to the already existing file, so that previous work is kept.

### CODE REVIEW

**Comment by mromanello** [comment]
This is cool and useful. Couple of things:
- explain a bit this behavior in the docstring of `compress_issues`
- does there need to be a `--incremental` flag in the generic CLI? or is this the default behavior?
- "if the file exists": here you mean locally, right (= no check on S3)?

**Comment by ehoelzl** [comment]
- The `--incremental` flag is already in the generic script. It detects the canonical issues in the `output_dir` and filters them out (not on S3).
However, it might be that we are re-running the importer on a few issues that are missing, and it will consequently overwrite the compressed file.
- It would be useful to do it also for S3, by checking if the file exists, download it, update it and re-upload.
- Will update the docstring.

Should I also implement the same behavior for S3 Upload ?

**Comment by mromanello** [comment]
> * The `--incremental` flag is already in the generic script. It detects the canonical issues in the `output_dir` and filters them out (not on S3).

ok, perfect, it must have been in a commit not included in the PR. 

> * It would be useful to do it also for S3, by checking if the file exists, download it, update it and re-upload.

I'd say not yet. I'd like to implement a check on s3 at the time of upload, and see whether that's enough.

**Comment by mromanello** [comment]
last change, set version == `0.9.1`, then I will merge

**Pull request merged**
